#!/usr/bin/env bash

function fp() {
    echo `pwd`/"$1"
}

script/setup-deps-edn builds
SRC=`fp src`
cd builds
clojure -J-Xmx3G ../script/build $SRC
echo "Testing with Node"
node -max-old-space-size=3072 main.js
cd ..
