#!/usr/bin/env bash

while [ $# -gt 0 ]
do
  case "$1" in
    -Sdeps)
      shift
      export DEPS="${1}"
      shift
      ;;
    *)
      break
      ;;
  esac
done

checkSucceeded() {
    CMD_RESULT=$?
    if [ $CMD_RESULT != 0 ]; then
        exit $CMD_RESULT
    fi
}

script/test-pre
checkSucceeded
script/test-part 1
checkSucceeded
script/test-part 2
checkSucceeded
script/test-part 3
checkSucceeded
script/test-part 4
checkSucceeded
script/test-part 5
checkSucceeded
script/test-post
