#!/usr/bin/env bash

script/test-pre
script/test-part 1
script/test-part 2
script/test-part 3
script/test-part 4
script/test-part 5
script/test-part 6
script/test-part 7
script/test-part 8
script/test-part 9
script/test-part 10
script/test-post
